Repository USYDUniTrack/unitrack, pull requests merged in 2023-12, with the labels that each got.

#16 Add new app to project
  ad
  db.sqlite3
  static/scss/_navbar.scss
  static/scss/global.scss
  templates/components/unit_search.html
  templates/unit_page.html
  templates/unit_search.html
  unitrack/models.py
  unitrack/settings.py
  unitrack/urls.py
  unitrack/views.py
  units/__init__.py
  units/admin.py
  units/apps.py
  units/migrations/0001_initial.py
  units/migrations/0002_rename_units_unit.py
  units/migrations/0003_rename_unit_units.py
  units/migrations/__init__.py
  units/models.py
  units/tests.py
  units/urls.py
  units/views.py
Labels: enhancement

#21 Add start.sh and update README
  .gitignore
  README.md
  start.sh
Labels: documentation

#23 Fix settings.py
  start.sh
  static/CACHE/css/global.61540fdd103e.css
  static/CACHE/css/global.7b0d14b7fb1a.css
  static/CACHE/css/global.c95f8178a5c9.css
  static/CACHE/css/global.d6ea004e91ed.css
  static/CACHE/css/global.eb4008b0ad93.css
  static/CACHE/css/global.f6f21020174c.css
  static/scss/_navbar.scss
  static/scss/global.scss
  templates/base.html
  templates/home.html
  unitrack/models.py
  unitrack/settings.py
  unitrack/urls.py
Labels: bug, documentation
